In [27]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os


In [28]:
hd_df = pd.read_csv('../Resources/heart.csv')
hd_df = hd_df[['age', 'gender','height','weight','ap_hi','ap_lo',
               'cholesterol','gluc','smoke','alco','active','cardio']]
hd_df['age'] = (hd_df['age']/365).apply(np.floor).astype(int)
hd_df.head()

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0   50       2     168    62.0    110     80            1     1      0     0   
1   55       1     156    85.0    140     90            3     1      0     0   
2   51       1     165    64.0    130     70            3     1      0     0   
3   48       2     169    82.0    150    100            1     1      0     0   
4   47       1     156    56.0    100     60            1     1      0     0   

   active  cardio  
0       1       0  
1       1       1  
2       0       1  
3       1       1  
4       0       0

In [29]:
cardio_df = hd_df['cardio']
hd_df = hd_df[['age', 'gender','height','weight','ap_hi','ap_lo',
               'cholesterol','gluc','smoke','alco','active']]
X = hd_df
y = cardio_df
print(X.shape, y.shape)

(70000, 11) (70000,)


In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler as ss


In [6]:
numeric_features = ['age', 'height',  'weight', 'ap_hi', 'ap_lo']
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', ss())])

categorical_features = ['cholesterol', 'gluc', 'smoke', 'alco', 'active']
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)])

# Append classifier to preprocessing pipeline.
# Now we have a full prediction pipeline.
clf = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', LogisticRegression())])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = clf.fit(X_train, y_train)
model
print("model score: %.3f" % clf.score(X_test, y_test))

model score: 0.719


In [7]:
param_grid = {
    'preprocessor__num__imputer__strategy': ['mean', 'median'],
    'classifier__C': [0.1, 1.0, 10, 100],
}

grid_search = GridSearchCV(clf, param_grid, cv=10)
grid_search.fit(X_train, y_train)

print(("best logistic regression from grid search: %.3f"
       % grid_search.score(X_test, y_test)))

best logistic regression from grid search: 0.719


In [32]:
import pickle

In [9]:
pickle.dump(grid_search, open('logistical_regression_grid_search.pkl', 'wb'))

In [33]:
loaded_model = pickle.load(open('logistical_regression_grid_search.pkl', 'rb'))
# result = loaded_model.score(X_test, y_test)
# print(result)

In [34]:
model = LogisticRegression(fit_intercept = False)
mdl = model.fit(X, y)
model.coef_

/Users/dotcal/anaconda3/envs/PythonDataanalytics/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([[ 3.75857142e-02,  2.67994529e-01, -4.96559538e-02,
         1.85787878e-02,  3.30320225e-02,  3.59712388e-04,
         5.07205605e-01, -1.50463918e-01, -7.78509079e-02,
        -1.07915028e-01, -3.03873248e-01]])

In [35]:
X = np.array([35,1,165,80.0,140,100,3,1,1,0,1])

model.predict((X.reshape(1,-1)))

array([1])

In [36]:
[ 32   2 178 125 100  70   2   1   0   0   1]

X = np.array([ 32   2 178 125 100  70   2   1   0   0   1])

model.predict((X.reshape(1,-1)))

SyntaxError: invalid syntax (<ipython-input-36-49fff0abbeef>, line 1)